version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: spa-container
    environment:
      POSTGRES_USER: kata
      POSTGRES_PASSWORD: aightwhatever
      POSTGRES_DB: spa-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: spa-redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
