#!/usr/bin/env bash

CLIENTDIR="$HOME/another_test/client_utils"
SERVERDIR="$HOME/sms-backend"

sleep 1

source $SERVERDIR/psyops/env/bin/activate && pip install -r requirements.txt

cd $SERVERDIR && yarn run dev:db && yarn run dev && cd $CLIENTDIR

sleep 5




